import {
  CCard,
  CCardBody,
  CCardHeader,
  CButton,
  CTable,
  CTableHead,
  CTableRow,
  CTableHeaderCell,
  CTableBody,
  CTableDataCell,
  CBadge,
  CFormInput,
  CFormSelect,
  CRow,
  CCol,
  CSpinner,
  CAlert,
  CModal,
  CModalHeader,
  CModalTitle,
  CModalBody,
  CModalFooter,
  CFormTextarea,
} from '@coreui/react'

import { useEffect, useState } from 'react'
import axios from 'axios'
import Swal from 'sweetalert2'

const StaffPenalties = () => {
  const API_URL = import.meta.env.VITE_BACKEND_URL

  const [loading, setLoading] = useState(true)
  const [processing, setProcessing] = useState(false)
  const [error, setError] = useState('')
  const [penalties, setPenalties] = useState([])
  const [selectedPenalty, setSelectedPenalty] = useState(null)
  const [visible, setVisible] = useState(false)

  const [filters, setFilters] = useState({
    search: '',
    status: '',
    penaltyType: '',
    startDate: '',
    endDate: '',
  })

  const [actionReason, setActionReason] = useState('')

  const token = localStorage.getItem('token')

  const authConfig = {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  }

  const getPenalties = async () => {
    try {
      setLoading(true)
      setError('')

      const response = await axios.get(`${API_URL}api/staff-penalties`, {
        ...authConfig,
        params: filters,
      })

      setPenalties(response.data.penalties || [])
    } catch (error) {
      console.error(error)

      setError(error.response?.data?.message || 'Unable to load staff penalties.')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    getPenalties()
  }, [])

  const handleFilterChange = (e) => {
    const { name, value } = e.target

    setFilters((previous) => ({
      ...previous,
      [name]: value,
    }))
  }

  const applyFilters = () => {
    getPenalties()
  }

  const clearFilters = () => {
    const clearedFilters = {
      search: '',
      status: '',
      penaltyType: '',
      startDate: '',
      endDate: '',
    }

    setFilters(clearedFilters)

    setTimeout(() => {
      getPenalties()
    }, 0)
  }

  const openActionModal = (penalty) => {
    setSelectedPenalty(penalty)
    setActionReason('')
    setVisible(true)
  }

  const performAction = async (action) => {
    if (!selectedPenalty) return

    try {
      setProcessing(true)

      await axios.put(
        `${API_URL}api/v1/staff-penalties/${selectedPenalty.id}/${action}`,
        {
          reason: actionReason,
        },
        authConfig,
      )

      setVisible(false)
      await getPenalties()

      Swal.fire({
        icon: 'success',
        title: 'Success',
        text: `Penalty ${action} successfully.`,
      })
    } catch (error) {
      console.error(error)

      Swal.fire({
        icon: 'error',
        title: 'Action Failed',
        text: error.response?.data?.message || 'Unable to process this penalty.',
      })
    } finally {
      setProcessing(false)
    }
  }

  const formatCurrency = (amount) => {
    return new Intl.NumberFormat('en-NG', {
      style: 'currency',
      currency: 'NGN',
      minimumFractionDigits: 2,
    }).format(Number(amount || 0))
  }

  const getStatusBadge = (status) => {
    const statusColors = {
      pending: 'warning',
      approved: 'success',
      waived: 'secondary',
      rejected: 'danger',
      paid: 'info',
    }

    return (
      <CBadge color={statusColors[status] || 'secondary'}>
        {String(status || 'pending').toUpperCase()}
      </CBadge>
    )
  }

  const getPenaltyTypeLabel = (type) => {
    const labels = {
      late: 'Late Arrival',
      absence: 'Absence',
      movement_overstay: 'Movement Overstay',
      overtime: 'Overtime',
      other: 'Other',
    }

    return labels[type] || type || 'Unknown'
  }

  if (loading) {
    return (
      <div className="d-flex justify-content-center py-5">
        <CSpinner color="primary" />
      </div>
    )
  }

  return (
    <>
      <CCard className="shadow-sm">
        <CCardHeader>
          <div className="d-flex justify-content-between align-items-center">
            <div>
              <h5 className="mb-1">Staff Penalties</h5>
              <small className="text-medium-emphasis">
                Review and manage penalties automatically generated by attendance.
              </small>
            </div>

            <CBadge color="primary">{penalties.length} Records</CBadge>
          </div>
        </CCardHeader>

        <CCardBody>
          {error && <CAlert color="danger">{error}</CAlert>}

          {/* FILTERS */}
          <CCard className="mb-4 border">
            <CCardBody>
              <CRow className="g-3">
                <CCol md={3}>
                  <CFormInput
                    label="Search Staff"
                    name="search"
                    placeholder="Name or staff ID"
                    value={filters.search}
                    onChange={handleFilterChange}
                  />
                </CCol>

                <CCol md={2}>
                  <CFormSelect
                    label="Status"
                    name="status"
                    value={filters.status}
                    onChange={handleFilterChange}
                    options={[
                      { label: 'All Statuses', value: '' },
                      { label: 'Pending', value: 'pending' },
                      { label: 'Approved', value: 'approved' },
                      { label: 'Waived', value: 'waived' },
                      { label: 'Rejected', value: 'rejected' },
                      { label: 'Paid', value: 'paid' },
                    ]}
                  />
                </CCol>

                <CCol md={3}>
                  <CFormSelect
                    label="Penalty Type"
                    name="penaltyType"
                    value={filters.penaltyType}
                    onChange={handleFilterChange}
                    options={[
                      { label: 'All Types', value: '' },
                      { label: 'Late Arrival', value: 'late' },
                      { label: 'Absence', value: 'absence' },
                      {
                        label: 'Movement Overstay',
                        value: 'movement_overstay',
                      },
                      { label: 'Overtime', value: 'overtime' },
                      { label: 'Other', value: 'other' },
                    ]}
                  />
                </CCol>

                <CCol md={2}>
                  <CFormInput
                    type="date"
                    label="Start Date"
                    name="startDate"
                    value={filters.startDate}
                    onChange={handleFilterChange}
                  />
                </CCol>

                <CCol md={2}>
                  <CFormInput
                    type="date"
                    label="End Date"
                    name="endDate"
                    value={filters.endDate}
                    onChange={handleFilterChange}
                  />
                </CCol>

                <CCol md={12}>
                  <div className="d-flex gap-2">
                    <CButton color="primary" onClick={applyFilters}>
                      Apply Filters
                    </CButton>

                    <CButton color="secondary" variant="outline" onClick={clearFilters}>
                      Clear
                    </CButton>
                  </div>
                </CCol>
              </CRow>
            </CCardBody>
          </CCard>

          {/* PENALTIES TABLE */}
          <CTable responsive hover align="middle">
            <CTableHead>
              <CTableRow>
                <CTableHeaderCell>Staff</CTableHeaderCell>
                <CTableHeaderCell>Penalty Type</CTableHeaderCell>
                <CTableHeaderCell>Reason</CTableHeaderCell>
                <CTableHeaderCell>Amount</CTableHeaderCell>
                <CTableHeaderCell>Date</CTableHeaderCell>
                <CTableHeaderCell>Status</CTableHeaderCell>
                <CTableHeaderCell>Action</CTableHeaderCell>
              </CTableRow>
            </CTableHead>

            <CTableBody>
              {penalties.length === 0 ? (
                <CTableRow>
                  <CTableDataCell colSpan={7} className="text-center py-4">
                    No staff penalties found.
                  </CTableDataCell>
                </CTableRow>
              ) : (
                penalties.map((penalty) => (
                  <CTableRow key={penalty.id}>
                    <CTableDataCell>
                      <strong>
                        {penalty.staff?.user?.name ||
                          penalty.staff?.name ||
                          penalty.staffName ||
                          'Unknown Staff'}
                      </strong>

                      <div className="small text-medium-emphasis">
                        {penalty.staff?.position || penalty.position || ''}
                      </div>
                    </CTableDataCell>

                    <CTableDataCell>{getPenaltyTypeLabel(penalty.penaltyType)}</CTableDataCell>

                    <CTableDataCell>
                      <span title={penalty.reason}>{penalty.reason || 'No reason provided'}</span>
                    </CTableDataCell>

                    <CTableDataCell>
                      <strong>{formatCurrency(penalty.amount)}</strong>
                    </CTableDataCell>

                    <CTableDataCell>
                      {penalty.penaltyDate
                        ? new Date(penalty.penaltyDate).toLocaleDateString('en-NG')
                        : penalty.createdAt
                          ? new Date(penalty.createdAt).toLocaleDateString('en-NG')
                          : '--'}
                    </CTableDataCell>

                    <CTableDataCell>{getStatusBadge(penalty.status)}</CTableDataCell>

                    <CTableDataCell>
                      <CButton
                        size="sm"
                        color="info"
                        variant="outline"
                        onClick={() => openActionModal(penalty)}
                      >
                        Review
                      </CButton>
                    </CTableDataCell>
                  </CTableRow>
                ))
              )}
            </CTableBody>
          </CTable>
        </CCardBody>
      </CCard>

      {/* ACTION MODAL */}
      <CModal visible={visible} onClose={() => setVisible(false)} backdrop="static">
        <CModalHeader>
          <CModalTitle>Review Staff Penalty</CModalTitle>
        </CModalHeader>

        <CModalBody>
          {selectedPenalty && (
            <>
              <div className="mb-3">
                <strong>Staff:</strong>{' '}
                {selectedPenalty.staff?.user?.name ||
                  selectedPenalty.staff?.name ||
                  selectedPenalty.staffName ||
                  'Unknown Staff'}
              </div>

              <div className="mb-3">
                <strong>Penalty Type:</strong> {getPenaltyTypeLabel(selectedPenalty.penaltyType)}
              </div>

              <div className="mb-3">
                <strong>Amount:</strong> {formatCurrency(selectedPenalty.amount)}
              </div>

              <div className="mb-3">
                <strong>Reason:</strong>
                <p className="text-medium-emphasis">
                  {selectedPenalty.reason || 'No reason provided'}
                </p>
              </div>

              <div className="mb-3">
                <strong>Current Status:</strong> {getStatusBadge(selectedPenalty.status)}
              </div>

              <CFormTextarea
                rows={3}
                label="Action Reason"
                value={actionReason}
                onChange={(e) => setActionReason(e.target.value)}
                placeholder="Enter reason for approving, waiving or rejecting this penalty..."
              />
            </>
          )}
        </CModalBody>

        <CModalFooter>
          <CButton color="secondary" variant="outline" onClick={() => setVisible(false)}>
            Close
          </CButton>

          <CButton
            color="danger"
            variant="outline"
            disabled={processing}
            onClick={() => performAction('reject')}
          >
            Reject
          </CButton>

          <CButton color="secondary" disabled={processing} onClick={() => performAction('waive')}>
            Waive
          </CButton>

          <CButton color="success" disabled={processing} onClick={() => performAction('approve')}>
            {processing ? 'Processing...' : 'Approve'}
          </CButton>
        </CModalFooter>
      </CModal>
    </>
  )
}

export default StaffPenalties
